drop table if exists vinyl CASCADE;
create table vinyl (id integer generated by default as identity, size integer not null, album varchar(255) not null, artist varchar(255) not null, primary key (id));
